name: Run CICD
on:
  push:
    branches:
      - 'master'
jobs:
  cidc:
    environment: prod
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
          distribution: 'adopt'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          gradle-version: 7.1
      - name: Upload to Codecov
        run: bash <(curl -s https://codecov.io/bash)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_REPOSITORYNAME }}:latest,${{ secrets.DOCKERHUB_REPOSITORYNAME }}:${{ github.sha }}
